//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tattoo.Domain.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArtWork
    {
        public int Id { get; set; }
        public string ArtImage { get; set; }
        public string ArtDesc { get; set; }
        public int ArtistId { get; set; }
        public Nullable<bool> ShowOnIntroScreen { get; set; }
    
        public virtual Artist Artist { get; set; }
    }
}
