//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tattoo.Domain.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyProfile
    {
        public int Id { get; set; }
        public string Intro { get; set; }
        public string Title { get; set; }
        public string HomepageImage { get; set; }
        public string CompanyAddress { get; set; }
        public string ContactNumber { get; set; }
    }
}
