CREATE TABLE [dbo].[ArtWork]
(
	[Id] BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	[ArtImage] NVARCHAR(100) NOT NULL,
	[ArtDesc] NVARCHAR(200),
	[ArtistId] INT NOT NULL CONSTRAINT FK_ArtWork_Artist FOREIGN KEY REFERENCES Artist(Id),
	[ShowOnIntroScreen] BIT DEFAULT 0
)
