CREATE TABLE [dbo].[Credentials]
(
	[Id] INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	[UserName] VARCHAR(20) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL UNIQUE,
	[Password]  VARCHAR(100) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL,
	[FullName] NVARCHAR(50) NOT NULL
)
